### PR TITLE
Release/1.3.1

### PR DESCRIPTION
**Pull request by hkellaway**
Updates to facilitate uploading to App Store

* Set development team setting
* Added missing app icons
* Added missing orientations to support iPad multitask

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Hi, I hope you don't mind my chiming in here.

I took a look at the Travis log for the most recent commit in this PR, and I noticed this error:
https://travis-ci.org/RefugeRestrooms/refugerestrooms-ios/builds/297091133#L722

Which says that `iRate.m` won't compile. I looked up [iRate](https://github.com/nicklockwood/iRate) and it seems development is discontinued, and it's no longer maintained beyond Xcode 8.3.

Maybe that dependency needs to be removed/replaced?

**Comment by hkellaway** [comment]
for some reason I can’t see the logs. I have to look into his more. 

for anyone looking to assist - the objective of this release is just succeeding in getting a new release to the App Store and one that uses https. one big issue being that this code base is super old at this point and uses a lot of libraries with versions that are no longer supported

**Comment by DeeDeeG** [comment]
I don't know what happened to the logs. I was able to view them enough to find out about iRate not compiling, then after a few times refreshing the log it gave me errors like you're saying.

To get the log back and viewable, I would personally just check this branch out in git, `git commit --amend` to re-calculate the latest commit with a new commit hash, and push to this PR's branch with `git push -f`

That way Travis should see it as a brand new commit and run the tests over again. (And should give a fresh, not-broken log page?)

I am not a mobile app developer myself, but I am pretty handy with troubleshooting stuff, and I have compiled some code from source before, so hopefully I can be of some assistance with getting this version of the app rolling. If that sounds good, I'm available and interested!

**Comment by hkellaway** [comment]
@DeeDeeG do you have an iPhone? i'll can add you to the TestFlight build so you can test pre-release. if yr interested in that, email me your email address - hello@harlankellaway.com

**Pull request closed without merging**
